'''

Creates the Ansible inventory file (inv.yml) based on the
parameter server and worker node IPs in settings_dist.py

'''

from settings_dist import PS_HOSTS, WORKER_HOSTS

with open('inv.yml','w') as txt_file:

	txt_file.write('# These are the nodes that will be used in the distributed TensorFlow training\n')
	txt_file.write('# This file is auto-generated by the list in settings_dist.py\n')
	txt_file.write('# DO NOT EDIT\n\n')
	txt_file.write('[nodes]\n')

	for x in PS_HOSTS:
		txt_file.write('{}\n'.format(x))

	for x in WORKER_HOSTS:
		txt_file.write('{}\n'.format(x))

